In [85]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [86]:
df = pd.read_csv("C:\\Users\\srinivas\\Desktop\\Innomatics Intership\\ML task\\reviews_badminton\\data.csv")

In [87]:
df.head()

Reviewer Name               Review Title  \
0            Kamal Suresh               Nice product   
1       Flipkart Customer     Don't waste your money   
2  A. S. Raja Srinivasan   Did not meet expectations   
3     Suresh Narayanasamy                       Fair   
4               ASHIK P A                Over priced   

               Place of Review  Up Votes  Down Votes     Month  \
0   Certified Buyer, Chirakkal     889.0        64.0  Feb 2021   
1   Certified Buyer, Hyderabad     109.0         6.0  Feb 2021   
2  Certified Buyer, Dharmapuri      42.0         3.0  Apr 2021   
3     Certified Buyer, Chennai      25.0         1.0       NaN   
4                          NaN     147.0        24.0  Apr 2016   

                                         Review text  Ratings  
0  Nice product, good quality, but price is now r...        4  
1  They didn't supplied Yonex Mavis 350. Outside ...        1  
2  Worst product. Damaged shuttlecocks packed in ...        1  
3  Quite O. K. , but nowadays  the quality of the...        3  
4  Over pricedJust â?¹620 ..from retailer.I didn'...        1

In [88]:
df.shape

(8518, 8)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8518 entries, 0 to 8517
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Reviewer Name    8508 non-null   object 
 1   Review Title     8508 non-null   object 
 2   Place of Review  8468 non-null   object 
 3   Up Votes         8508 non-null   float64
 4   Down Votes       8508 non-null   float64
 5   Month            8053 non-null   object 
 6   Review text      8510 non-null   object 
 7   Ratings          8518 non-null   int64  
dtypes: float64(2), int64(1), object(5)
memory usage: 532.5+ KB


In [90]:
df.columns = df.columns.str.strip()
df.columns

Index(['Reviewer Name', 'Review Title', 'Place of Review', 'Up Votes',
       'Down Votes', 'Month', 'Review text', 'Ratings'],
      dtype='object')

In [91]:
df.isnull().sum().sort_values(ascending = False)

Month              465
Place of Review     50
Reviewer Name       10
Review Title        10
Up Votes            10
Down Votes          10
Review text          8
Ratings              0
dtype: int64

In [92]:
df1=df.dropna()

In [93]:
df1.isnull().sum().sort_values(ascending = False)

Reviewer Name      0
Review Title       0
Place of Review    0
Up Votes           0
Down Votes         0
Month              0
Review text        0
Ratings            0
dtype: int64

In [94]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8013 entries, 0 to 8507
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Reviewer Name    8013 non-null   object 
 1   Review Title     8013 non-null   object 
 2   Place of Review  8013 non-null   object 
 3   Up Votes         8013 non-null   float64
 4   Down Votes       8013 non-null   float64
 5   Month            8013 non-null   object 
 6   Review text      8013 non-null   object 
 7   Ratings          8013 non-null   int64  
dtypes: float64(2), int64(1), object(5)
memory usage: 563.4+ KB


In [95]:
thresholud_rating = 3
def map_rating_to_sentiment(rating):
    if rating > thresholud_rating:
        return 'positive'
    elif rating == thresholud_rating:
        return 'neutral'
    else:
        return 'negative'

In [96]:
df1['sentiment'] = df1['Ratings'].apply(map_rating_to_sentiment)

C:\Users\srinivas\AppData\Local\Temp\ipykernel_17044\1358400811.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['sentiment'] = df1['Ratings'].apply(map_rating_to_sentiment)


In [97]:
df1.head(15)

Reviewer Name               Review Title  \
0             Kamal Suresh               Nice product   
1        Flipkart Customer     Don't waste your money   
2   A. S. Raja Srinivasan   Did not meet expectations   
5              Baji Sankar      Mind-blowing purchase   
6        Flipkart Customer                  Must buy!   
7        Flipkart Customer             Classy product   
8           Jafar  Qureshi              Great product   
9                 Bheemesh                  Just wow!   
10              ABBCD Zggg                  Just wow!   
11        Sadashivu Shetty          Terrific purchase   
12              Abhishek m          Worth every penny   
13                Hashim A  Did not meet expectations   
14           Karan Dattani          Worth every penny   
15             Divya Mohan                  Brilliant   
16                Harish R    I think it is duplicate   

                     Place of Review  Up Votes  Down Votes     Month  \
0         Certified Buyer, Chirakkal     889.0        64.0  Feb 2021   
1         Certified Buyer, Hyderabad     109.0         6.0  Feb 2021   
2        Certified Buyer, Dharmapuri      42.0         3.0  Apr 2021   
5         Certified Buyer, Hyderabad     173.0        45.0  Oct 2018   
6        Certified Buyer, Doom Dooma     403.0       121.0  Jan 2020   
7            Certified Buyer, Panjim      59.0        13.0  Oct 2018   
8           Certified Buyer, Sheopur      14.0         1.0  Aug 2018   
9           Certified Buyer, Kurnool      50.0        12.0  May 2018   
10  Certified Buyer, Channarayapatna      57.0        16.0  Jun 2020   
11        Certified Buyer, Mangalore     146.0        52.0  Sep 2016   
12       Certified Buyer, Chengannur     142.0        53.0  Jun 2018   
13           Certified Buyer, Panoor      22.0         5.0  Mar 2021   
14           Certified Buyer, Mumbai      23.0         6.0  Mar 2019   
15        Certified Buyer, Darbhanga      71.0        29.0  Oct 2016   
16        Certified Buyer, Bangalore      81.0        35.0  Feb 2018   

                                          Review text  Ratings sentiment  
0   Nice product, good quality, but price is now r...        4  positive  
1   They didn't supplied Yonex Mavis 350. Outside ...        1  negative  
2   Worst product. Damaged shuttlecocks packed in ...        1  negative  
5   Good quality product. Delivered on time.READ MORE        5  positive  
6   BEST PURCHASE It is a good quality and is more...        5  positive  
7            Good quality original shuttles.READ MORE        5  positive  
8                                    AwesomeREAD MORE        5  positive  
9                     nice original productsREAD MORE        5  positive  
10  This GREEN CAP SHUTTLECOCK is really AWESOME. ...        5  positive  
11                         Best in class....READ MORE        5  positive  
12  it's genuine and price is less than our near b...        5  positive  
13  This is the second time i am getting an opened...        1  negative  
14  really satisfied with the quality and the prom...        5  positive  
15                                       NycREAD MORE        5  positive  
16  I usually buy them the same model but this did...        1  negative

In [99]:
y = df1['sentiment']
X = df1[['Review text']]

In [100]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [101]:
X_train.head(10)

Review text
250   Product is good as like as bought in the open ...
7735                                Love it...READ MORE
2805                                      GoodREAD MORE
4914                                     superREAD MORE
1539                                 excellentREAD MORE
2159                                      GoodREAD MORE
1575                                      NiceREAD MORE
2299  Best product for beginners playing outside.REA...
7207                              good productREAD MORE
1927                                 Very goodREAD MORE

In [102]:
y_train.head(10)

250     positive
7735    positive
2805    positive
4914     neutral
1539    positive
2159    positive
1575    positive
2299    positive
7207    positive
1927    positive
Name: sentiment, dtype: object

In [103]:
X_train.shape

(6410, 1)

In [104]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [105]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [106]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\srinivas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\srinivas\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [107]:
def preprocess(raw_text, flag):
    # Removing special characters and digits
    sentence = re.sub("[^a-zA-Z]", " ", raw_text)
    
    # change sentence to lower case
    sentence = sentence.lower()

    # tokenize into words
    tokens = sentence.split()
    
    # remove stop words                
    clean_tokens = [t for t in tokens if not t in stopwords.words("english")]
    
    if clean_tokens and clean_tokens[-1] == 'read':
        clean_tokens = clean_tokens[:-1]
    
    # Stemming/Lemmatization
    if(flag == 'stem'):
        clean_tokens = [stemmer.stem(word) for word in clean_tokens]
    else:
        clean_tokens = [lemmatizer.lemmatize(word) for word in clean_tokens]
    
    return pd.Series([" ".join(clean_tokens), len(clean_tokens)])

In [108]:
temp_df = X_train['Review text'].apply(lambda x: preprocess(x, 'stem'))

temp_df.head()

0   1
250   product good like bought open market price als...  16
7735                                               love   1
2805                                           goodread   1
4914                                          superread   1
1539                                      excellentread   1

In [109]:
temp_df.columns = ['clean_text_stem', 'text_length_stem']

temp_df.head()

clean_text_stem  text_length_stem
250   product good like bought open market price als...                16
7735                                               love                 1
2805                                           goodread                 1
4914                                          superread                 1
1539                                      excellentread                 1

In [110]:
X_train = pd.concat([X_train, temp_df], axis=1)

X_train.head()

Review text  \
250   Product is good as like as bought in the open ...   
7735                                Love it...READ MORE   
2805                                      GoodREAD MORE   
4914                                     superREAD MORE   
1539                                 excellentREAD MORE   

                                        clean_text_stem  text_length_stem  
250   product good like bought open market price als...                16  
7735                                               love                 1  
2805                                           goodread                 1  
4914                                          superread                 1  
1539                                      excellentread                 1

In [111]:
temp_df = X_train['Review text'].apply(lambda x: preprocess(x, 'lemma'))

temp_df.head()

0   1
250   product good like bought open market price als...  16
7735                                               love   1
2805                                           goodread   1
4914                                          superread   1
1539                                      excellentread   1

In [112]:
temp_df.columns = ['clean_text_lemma', 'text_length_lemma']

temp_df.head()

clean_text_lemma  text_length_lemma
250   product good like bought open market price als...                 16
7735                                               love                  1
2805                                           goodread                  1
4914                                          superread                  1
1539                                      excellentread                  1

In [113]:
X_train = pd.concat([X_train, temp_df], axis=1)

X_train.head()

Review text  \
250   Product is good as like as bought in the open ...   
7735                                Love it...READ MORE   
2805                                      GoodREAD MORE   
4914                                     superREAD MORE   
1539                                 excellentREAD MORE   

                                        clean_text_stem  text_length_stem  \
250   product good like bought open market price als...                16   
7735                                               love                 1   
2805                                           goodread                 1   
4914                                          superread                 1   
1539                                      excellentread                 1   

                                       clean_text_lemma  text_length_lemma  
250   product good like bought open market price als...                 16  
7735                                               love                  1  
2805                                           goodread                  1  
4914                                          superread                  1  
1539                                      excellentread                  1

In [114]:
X_train.head(10)

Review text  \
250   Product is good as like as bought in the open ...   
7735                                Love it...READ MORE   
2805                                      GoodREAD MORE   
4914                                     superREAD MORE   
1539                                 excellentREAD MORE   
2159                                      GoodREAD MORE   
1575                                      NiceREAD MORE   
2299  Best product for beginners playing outside.REA...   
7207                              good productREAD MORE   
1927                                 Very goodREAD MORE   

                                        clean_text_stem  text_length_stem  \
250   product good like bought open market price als...                16   
7735                                               love                 1   
2805                                           goodread                 1   
4914                                          superread                 1   
1539                                      excellentread                 1   
2159                                           goodread                 1   
1575                                           niceread                 1   
2299                    best product beginn play outsid                 5   
7207                                   good productread                 2   
1927                                           goodread                 1   

                                       clean_text_lemma  text_length_lemma  
250   product good like bought open market price als...                 16  
7735                                               love                  1  
2805                                           goodread                  1  
4914                                          superread                  1  
1539                                      excellentread                  1  
2159                                           goodread                  1  
1575                                           niceread                  1  
2299              best product beginner playing outside                  5  
7207                                   good productread                  2  
1927                                           goodread                  1

In [115]:
from sklearn.feature_extraction.text import CountVectorizer

vocab = CountVectorizer()

X_train_bow = vocab.fit_transform(X_train['clean_text_lemma'])

In [161]:
with open('C:\\Users\\srinivas\\Desktop\\Innomatics Intership\\ML task\\cv.pkl', 'wb') as f:
    pickle.dump(vocab, f)

In [116]:
X_train_bow

<6410x2523 sparse matrix of type '<class 'numpy.int64'>'
	with 21031 stored elements in Compressed Sparse Row format>

In [117]:
print("Total unique words:", len(vocab.vocabulary_))

print("Type of train features:", type(X_train_bow))

print("Shape of input data:", X_train_bow.shape)

Total unique words: 2523
Type of train features: <class 'scipy.sparse._csr.csr_matrix'>
Shape of input data: (6410, 2523)


In [118]:
print(X_train_bow.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [119]:
X_test.head(10)

Review text
1880        Nice product and delivered ontime.READ MORE
2188  Good one... On problem for  20 to 30 days..REA...
7075                                     SuperREAD MORE
4967             genuine product.....go for itREAD MORE
3822                                 Very niceREAD MORE
8280                   Good product for indoorREAD MORE
284   Absolutely good quality shuttles,and great pac...
778   It's original and it's the best.Go for it with...
3046                                      NiceREAD MORE
6453                                      niceREAD MORE

In [121]:
temp_df = X_test['Review text'].apply(lambda x: preprocess(x, 'lemma'))

temp_df.head()

0  1
1880  nice product delivered ontime  4
2188           good one problem day  4
7075                      superread  1
4967      genuine product go itread  4
3822                       niceread  1

In [122]:
temp_df.columns = ['clean_text_lemma', 'text_length_lemma']

temp_df.head()

clean_text_lemma  text_length_lemma
1880  nice product delivered ontime                  4
2188           good one problem day                  4
7075                      superread                  1
4967      genuine product go itread                  4
3822                       niceread                  1

In [123]:
X_test = pd.concat([X_test, temp_df], axis=1)

X_test.head()

Review text  \
1880        Nice product and delivered ontime.READ MORE   
2188  Good one... On problem for  20 to 30 days..REA...   
7075                                     SuperREAD MORE   
4967             genuine product.....go for itREAD MORE   
3822                                 Very niceREAD MORE   

                   clean_text_lemma  text_length_lemma  
1880  nice product delivered ontime                  4  
2188           good one problem day                  4  
7075                      superread                  1  
4967      genuine product go itread                  4  
3822                       niceread                  1

In [124]:
X_test_bow = vocab.transform(X_test['clean_text_lemma'])

In [138]:
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression()
classifier1.fit(X_train_bow, y_train)

C:\Users\srinivas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [139]:
y_train_pred = classifier1.predict(X_train_bow)

In [140]:
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_train, y_train_pred))

print(classification_report(y_train, y_train_pred))

0.9065522620904837
              precision    recall  f1-score   support

    negative       0.87      0.72      0.79       778
     neutral       0.94      0.26      0.40       456
    positive       0.91      0.99      0.95      5176

    accuracy                           0.91      6410
   macro avg       0.91      0.66      0.71      6410
weighted avg       0.91      0.91      0.89      6410



In [141]:
y_test_pred = classifier1.predict(X_test_bow)

In [142]:
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_test, y_test_pred))

print(classification_report(y_test, y_test_pred))

0.868995633187773
              precision    recall  f1-score   support

    negative       0.76      0.60      0.67       198
     neutral       0.50      0.08      0.13       119
    positive       0.89      0.98      0.93      1286

    accuracy                           0.87      1603
   macro avg       0.72      0.55      0.58      1603
weighted avg       0.84      0.87      0.84      1603



In [156]:
import pickle

In [160]:
with open('C:\\Users\\srinivas\\Desktop\\Innomatics Intership\\ML task\\classifier1.pkl', 'wb') as f:
    pickle.dump(classifier1, f)

In [143]:
from sklearn.tree import DecisionTreeClassifier
classifier2 = DecisionTreeClassifier()
classifier2.fit(X_train_bow, y_train)

DecisionTreeClassifier()

In [144]:
y_train_pred = classifier2.predict(X_train_bow)

In [145]:
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_train, y_train_pred))

print(classification_report(y_train, y_train_pred))

0.9507020280811233
              precision    recall  f1-score   support

    negative       0.91      0.91      0.91       778
     neutral       0.92      0.59      0.72       456
    positive       0.96      0.99      0.97      5176

    accuracy                           0.95      6410
   macro avg       0.93      0.83      0.87      6410
weighted avg       0.95      0.95      0.95      6410



In [146]:
y_test_pred = classifier2.predict(X_test_bow)

In [147]:
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_test, y_test_pred))

print(classification_report(y_test, y_test_pred))

0.8384279475982532
              precision    recall  f1-score   support

    negative       0.61      0.56      0.58       198
     neutral       0.24      0.09      0.13       119
    positive       0.89      0.95      0.92      1286

    accuracy                           0.84      1603
   macro avg       0.58      0.53      0.55      1603
weighted avg       0.81      0.84      0.82      1603



In [148]:
from sklearn.ensemble import RandomForestClassifier
classifier3 = RandomForestClassifier()
classifier3.fit(X_train_bow, y_train)

RandomForestClassifier()

In [149]:
y_train_pred = classifier3.predict(X_train_bow)

In [150]:
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_train, y_train_pred))

print(classification_report(y_train, y_train_pred))

0.9507020280811233
              precision    recall  f1-score   support

    negative       0.91      0.90      0.91       778
     neutral       0.98      0.56      0.71       456
    positive       0.95      0.99      0.97      5176

    accuracy                           0.95      6410
   macro avg       0.95      0.82      0.86      6410
weighted avg       0.95      0.95      0.95      6410



In [151]:
y_test_pred = classifier3.predict(X_test_bow)

In [152]:
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_test, y_test_pred))

print(classification_report(y_test, y_test_pred))

0.8577666874610106
              precision    recall  f1-score   support

    negative       0.72      0.55      0.62       198
     neutral       0.29      0.04      0.07       119
    positive       0.88      0.98      0.93      1286

    accuracy                           0.86      1603
   macro avg       0.63      0.52      0.54      1603
weighted avg       0.82      0.86      0.83      1603

